### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by alamoudimoh** [Ailme/homeassistant-openvpn-client-addon#4]
When i start the addon, i get the following

s6-overlay-suexec: fatal: can only run as pid 1

Plus, where should I put my client vpn username and password

**Comment by Gradlon** [comment]
Same here.
Any Idea how we can fix this?

**Comment by Gradlon** [comment]
> Same here. Any Idea how we can fix this?

Stumbled opon this
https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

**Comment by Gradlon** [comment]
I solved the issue:
clone the add-on to your addons folder and add "init: false" as described in the article above.
Restart home assistant and install the local add-on.
Voila it works.

**Comment by barneyman** [comment]
i've added a PR for this fix

**Comment by newone1307** [comment]
Could you please describe in detail how did you solved it?

What I've tried
.copy OpenVPN addon to /addon
add config.yaml 

name: "OpenVPN"
description: "openVPN test"
version: "1.0.0"
slug: "OpenVPN_client"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

but it doesn't work
I'm new to HA, I'm using HAOS on RPI3b+

**Comment by maxbrandes** [comment]
> I solved the issue:
> clone the add-on to your addons folder and add "init: false" as described in the article above.
> Restart home assistant and install the local add-on.
> Voila it works.

How do I clone the add-on? I am running Home Assistant OS on a RPi4.
